a = input("Digite um valor: ")
print("O tipo primitivo desse valor é", type(a))
print("Só tem espaços?", a.isspace())
print("É um número?", a.isnumeric())
print("alfabético?", a.isalpha())
print("É alfanumérico?", a.isalnum())
print("Está em maiúsculas?", a.isupper())
print("Está em minúsculas?", a.islower())
print("Está capitalizada?", a.istitle())